### PR TITLE
Add favicon to storybook

### PR DESCRIPTION
**Pull request by maxjacobson**
When we deploy our storybook to github pages, the URL looks something
like: https://vimeo.github.io/iris/sb/main/

The storybook build does include a favicon at
https://vimeo.github.io/iris/sb/main/favicon.ico and it's fine (it's the
storybook logo). But the generated HTML does not include a link tag
telling the browser to use that favicon, and so it falls back to trying
to load a favicon from https://vimeo.github.io/favicon.ico which
responds with a 404.

We can add this magic `.storybook/manager-head.html` file to inject some
code into the head of the storybook, and do whatever we like.

In this case, I'm suggesting to use the flowers emoji as an homage to
the name of the project. We could also probably use a proper image if we
want...

Snippet via https://emojicon.dev/

Also shout out to @jacquelinemarchal for asking why there's no favicon and [nerd sniping](https://xkcd.com/356/) me into looking into how to add one.

### CODE REVIEW

**Comment by maxjacobson** [comment]
If you'd like to see a demo: https://vimeo.github.io/iris/sb/add-favicon/?path=/story/iris-welcome--welcome
Screen Shot 2022-06-29 at 19 04 55

**Comment by juliewongbandue** [comment]
lol this is great. Should we have a vimeo favicon though?

**Comment by maxjacobson** [comment]
> lol this is great. Should we have a vimeo favicon though?

yes probably 😞 😂 

OK updated!

Viewable here: https://vimeo.github.io/iris/sb/add-favicon/?path=/story/iris-welcome--welcome

Demo:

Screen Shot 2022-06-30 at 13 00 45

**Review by juliewongbandue — APPROVED** [review]
lgtm :)

**Pull request merged**
