### PR TITLE
Hide Sidebar Panel From Being Focusable If Hidden

### PR DESCRIPTION
**Pull request by kenneth-duverge**
**Storybook:** https://vimeo.github.io/iris/sb/fix-hidden-panel-focus/?path=/story/components-sidebar-props--attach

## What
Hides sidebar panel from being focusable when not active. Currently when the sidebar is attached to the right of the window a user is able to tab through the sidebar items and once they pass the last item in the sidebar, the sidebar panel is focused because it is a sibling element of the sidebar.

**Current Issue**
Panel Focus When Hidden-high

## How it does that?
Adds a `hidden` attribute to `PanelStyled`. If the panel is not active then `hidden` is true.

### CODE REVIEW

**Review by seanmcintyre — CHANGES_REQUESTED** [review]
Hi Kenneth. This breaks the current behavior of the Sidebar. The `hidden` attribute also has a controversial history (and can easily be overridden). I agree that the children of the Sidebar's panel should not be focusable once it is closed, but another method will be needed to accomplish this.

**Comment by kenneth-duverge** [comment]
> Hi Kenneth. This breaks the current behavior of the Sidebar. The `hidden` attribute also has a controversial history (and can easily be overridden). I agree that the children of the Sidebar's panel should not be focusable once it is closed, but another method will be needed to accomplish this.

Good call, I'm thinking of updating the `tabIndex` of the button since that is what's getting the focus.

```ts
tabIndex={!active ? -1 : 0}
```

**Comment by kenneth-duverge** [comment]
We could conditionally render the dismiss button 🤔 

```tsx
{panel && (
  <Dismiss
    aria-label="Dismiss"
    format="basic"
    icon={<DismissX />}
    onClick={close}
    variant="minimalTransparent"
  />
}
```

Also thought about using `framer-motion` and having it handle the panel transition animation

```tsx
<AnimatePresence exitBeforeEnter>
  {panel && (
    <MotionPanelStyled 
      variants={variants} 
      initial="hidden" 
      animate="visible" 
      exit="hidden"
     >
      ...
    </MotionPanelStyled>
  )}
</AnimatePresence>
```

**Comment by tylerthegrove** [comment]
@kenneth-duverge 

Since there will almost always be focusable content in the panel itself, I think we need a fuller solution than just the conditional rendering of the dismiss. 

Like you suggested I think framer motion could be a good solution. I've also put together this idea as well https://github.com/vimeo/iris/pull/132

**Comment by kenneth-duverge** [comment]
Ah okay, sounds good @tylerthegrove ! I'll go ahead and close this PR

**Pull request closed without merging**
